### ISSUE TITLE
configuration files

### ISSUE THREAD

**Issue by kffeng** [lntzm/MESM#3]
hello，dear team，When will the training configuration files of the other two data sets tacos and QVHighlights be updated?

**Comment by lntzm** [comment]
I mentioned it in [Issue 1](https://github.com/lntzm/MESM/issues/1#issuecomment-1991068908). And I will update soon.

**Comment by lntzm** [comment]
Hello, the configs of TACoS and QVHighlights are updated.
The provided results of QVHighlights are similar in the `val` split, I cannot check the performance of the `test` split since I have run out the submitting chances of the [Codelab](https://codalab.lisn.upsaclay.fr/competitions/6937). Nevertheless, I believe it will also work.
